name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - run: npm install
      - run: npm run lint:js --workspace=ember-cli-typedoc
      - run: npm test