name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: auto-dist-tag
        run: npx auto-dist-tag --write
        working-directory: packages/ember-cli-typedoc
      - name: copy readme
        run: cp README.md packages/ember-cli-typedoc/README.md
      - name: copy changelog
        run: cp CHANGELOG.md packages/ember-cli-typedoc/CHANGELOG.md

      - run: npm publish
        working-directory: packages/ember-cli-typedoc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
