name: Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: NPM install and test with coverage
      - uses: volta-cli/action@v1
      - run: npm install
      - run: npm run lint:js --workspace=ember-cli-typedoc
      - run: npm run test:coverage
